const PERMISOS = Object.freeze({
  CLASE_RESERVAR: "clase.reservar",
  CLASE_GESTIONAR: "clase.gestionar",
  PAGO_COBRAR: "pago.cobrar",
  PAGO_VER_PROPIO: "pago.ver_propio",
  PAGO_VER_TODOS: "pago.ver_todos",
  ASISTENCIA_ESCANEAR: "asistencia.escanear",
  ASISTENCIA_DENEGAR: "asistencia.denegar",
  USUARIO_GESTIONAR: "usuario.gestionar",
  EMPLEADO_GESTIONAR: "empleado.gestionar",
  ACTIVIDAD_GESTIONAR: "actividad.gestionar",
  REPORTE_VER: "reporte.ver",
});

const PERMISOS_LIST = Object.values(PERMISOS);

const { ROLES } = require("./roles");

const MATRIZ_ROL_PERMISOS = Object.freeze({
  [ROLES.ADMIN]: [
    PERMISOS.CLASE_RESERVAR,
    PERMISOS.CLASE_GESTIONAR,
    PERMISOS.PAGO_COBRAR,
    PERMISOS.PAGO_VER_PROPIO,
    PERMISOS.PAGO_VER_TODOS,
    PERMISOS.ASISTENCIA_ESCANEAR,
    PERMISOS.ASISTENCIA_DENEGAR,
    PERMISOS.USUARIO_GESTIONAR,
    PERMISOS.EMPLEADO_GESTIONAR,
    PERMISOS.ACTIVIDAD_GESTIONAR,
    PERMISOS.REPORTE_VER,
  ],
  [ROLES.RECEPCIONISTA]: [
    PERMISOS.CLASE_RESERVAR,
    PERMISOS.PAGO_COBRAR,
    PERMISOS.PAGO_VER_PROPIO,
    PERMISOS.PAGO_VER_TODOS,
    PERMISOS.ASISTENCIA_ESCANEAR,
    PERMISOS.ASISTENCIA_DENEGAR,
    PERMISOS.USUARIO_GESTIONAR,
  ],
  [ROLES.CLIENTE]: [
    PERMISOS.USUARIO_GESTIONAR,
    PERMISOS.CLASE_RESERVAR,
    PERMISOS.PAGO_VER_PROPIO,
  ],
});

module.exports = { PERMISOS, PERMISOS_LIST, MATRIZ_ROL_PERMISOS };
